version: '2'

services:
  traefik:
    image: traefik:1.7.9
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.DOMAIN"
      - "traefik.frontend.auth.basic=username:MD5PASSWORD"
  
networks:
  containers:
    external: true